Repository KBKN-Autonomous-Robotics-Lab/orange_navigation, pull requests merged in 2023-10, with the labels that each got.

#3 Add rviz plugin to start and resume navigation
  .clang-format
  .github/workflows/ci.yaml
  rviz2_plugins/CMakeLists.txt
  rviz2_plugins/include/rviz2_plugins/state_trigger_panel.h
  rviz2_plugins/package.xml
  rviz2_plugins/plugin_description.xml
  rviz2_plugins/src/state_trigger_panel.cpp
  waypoint_manager/lib/mymaplib.py
  waypoint_manager/lib/waypointlib.py
  waypoint_manager/manager_GUI.py
  waypoint_manager/test/map.pgm
  waypoint_manager/test/map.yaml
  waypoint_manager/test/waypoints.yaml
Labels: enhancement

#5 enabling clang_tidy, pylint and build_check
  .clang-tidy
  .github/workflows/ci.yaml
  rviz2_plugins/CMakeLists.txt
  rviz2_plugins/include/rviz2_plugins/state_trigger_panel.h
  rviz2_plugins/package.xml
Labels: enhancement

#11 Update README.md
  README.md
Labels: documentation

#7 Feature/waypoint navigation
  waypoint_navigation/launch/navigation2_core.launch.xml
  waypoint_navigation/launch/waypoint_nav.launch.xml
  waypoint_navigation/src/waypoint_nav.cpp
Labels: bug

#12 Feature/waypoint saver
  rviz2_plugins/CMakeLists.txt
  rviz2_plugins/include/rviz2_plugins/set_finish_panel.h
  rviz2_plugins/plugin_description.xml
  rviz2_plugins/src/set_finish_panel.cpp
  waypoint_navigation/CMakeLists.txt
  waypoint_navigation/include/waypoint_navigation/waypoint_saver.h
  waypoint_navigation/launch/waypoint_saver.launch.xml
  waypoint_navigation/package.xml
  waypoint_navigation/rviz_cfg/waypoint_saver.rviz
  waypoint_navigation/src/waypoint_saver.cpp
Labels: enhancement

#13 fix_waypoints_file
  waypoint_navigation/launch/waypoint_nav.launch.xml
Labels: enhancement

#15 Feature/tandem
  waypoint_navigation/CMakeLists.txt
  waypoint_navigation/config/switch_costmaps.yaml
  waypoint_navigation/include/waypoint_navigation/waypoint_nav.h
  waypoint_navigation/launch/navigation2_core.launch.xml
  waypoint_navigation/launch/waypoint_nav.launch.xml
  waypoint_navigation/package.xml
  waypoint_navigation/rviz_cfg/waypoint_nav.rviz
  waypoint_navigation/scripts/tandem_run_manager.py
  waypoint_navigation/src/waypoint_nav.cpp
  waypoint_navigation/waypoint_navigation/__init__.py
  waypoint_navigation/waypoints_cfg/waypoints.yaml
Labels: enhancement

#18 Feature/launch method
  waypoint_navigation/launch/navigation2_core.launch.xml
  waypoint_navigation/launch/waypoint_nav.launch.xml
  waypoint_navigation/launch/waypoint_saver.launch.xml
  waypoint_navigation/rviz_cfg/waypoint_nav.rviz
  waypoint_navigation/rviz_cfg/waypoint_saver.rviz
  waypoint_navigation/src/waypoint_saver.cpp
Labels: enhancement

#19 Add functioin to start from middle waypoint
  waypoint_navigation/include/waypoint_navigation/waypoint_nav.h
  waypoint_navigation/launch/waypoint_nav.launch.xml
  waypoint_navigation/src/waypoint_nav.cpp
Labels: enhancement
